# Generated by Django 4.0.6 on 2022-07-27 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0002_carmodel_oil_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='carmodel',
            name='desc',
            field=models.TextField(default=''),
        ),
    ]
